server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://jeet:jeet30042005@cluster0.hfvivxp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: hotelService
      auto-index-creation: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
