server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://jeet:jeet30042005@cluster0.hfvivxp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ratingService
      auto-index-creation: true
